### ISSUE TITLE
HTML5 input validation in Chrome prevents login

### ISSUE THREAD

**Issue by marcusmolchany** [AnomalyInnovations/serverless-stack-demo-client#1]
The [email input type in Login.js](https://github.com/AnomalyInnovations/serverless-stack-demo-client/blob/master/src/containers/Login.js#L100) prevents the form from being submitted for usernames in Chrome.

<img width="452" alt="screen shot 2017-03-12 at 10 47 09 pm" src="https://cloud.githubusercontent.com/assets/2160046/23842990/ddeb08a0-0775-11e7-864a-a391bbf2c78e.png">

**Comment by mfwhitman** [comment]
As a quick workaround, I've just changed the FormControl attribute from `type="email"` to `type="text"`

**Comment by jayair** [comment]
So we DO want this field to be `type="email"` since we want users to login with their email as their username (as opposed to creating a separate username and making the process a bit more complicated).

But we are running into this issue in Chrome because in the [Create a Cognito Test User](http://serverless-stack.com/chapters/create-a-cognito-test-user.html) chapter, we are directing folks to create a test user with a username instead of the email.

We'll fix that chapter shortly.

For now, if you already have a test user then go ahead and use the workaround @mfwhitman suggested (but I'm sure you guys figured that out already!).

**Comment by jayair** [comment]
Hey guys, we fixed the test user chapter and some other parts of the tutorial directing folks to create a test user with an email address instead of a username. So hopefully, people don't run into this issue anymore.

Here is the commit - https://github.com/AnomalyInnovations/serverless-stack-com/commit/29b748a4d98fd5b9a84252943621c3a4c456701c
