### ISSUE TITLE
Is AuthenticatedRoute.js really needed?

### ISSUE THREAD

**Issue by pig800509** [AnomalyInnovations/serverless-stack-demo-client#45]
Through app.js 
```
async componentDidMount() {
    try {
      if (await Auth.currentSession()) {
        this.userHasAuthenticated(true);
      }
    }
    catch(e) {
      if (e !== 'No current user') {
        alert(e);
      }
      this.props.history.push("/");   // Simply add this line to protect all path
    }
    this.setState({ isAuthenticating: false });
  }
```
Why do you want to use AuthenticatedRoute.js ?

**Comment by jayair** [comment]
@pig800509 The AuthenticatedRoute.js and the UnauthenticatedRoute.js are necessary to handle the login and logout when you don't load the app for the first time. So imagine you hit the logout and you need to redirect after the button is clicked. You can handle this by adding redirects in different spots. The two components just simplify the process so that the redirects are done is the same spot.

We talk about it here - https://serverless-stack.com/chapters/setup-secure-pages.html.

**Comment by pig800509** [comment]
OK thanks
